apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "e81c6b0d-e28f-4cfe-9c7c-2d61cf13d2cc"
    keyvaultName: "kv-n8n-aks"
    tenantId: "13066310-4802-4379-a550-cb9b1a540aaa"
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: n8n-encryption-key
          objectType: secret
  secretObjects:
    - secretName: n8n-container-env
      type: Opaque
      data:
        - objectName: db-user
          key: DB_POSTGRESDB_USER
        - objectName: db-password
          key: DB_POSTGRESDB_PASSWORD
        - objectName: n8n-encryption-key
          key: N8N_ENCRYPTION_KEY
