apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
  # n8n configuration options
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "psql-n8n-aks.postgres.database.azure.com"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "n8n"
  N8N_SECURE_COOKIE: "false"
  DB_POSTGRESDB_SSL_ENABLED: "true"
  DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED: "true"